@hostname = localhost
@port = 3000
@base-path = api
@version = v1
@combined-path = {{hostname}}:{{port}}/{{base-path}}/{{version}}
@url = http://{{combined-path}}

###
// Ping
GET http://{{hostname}}:{{port}}/ping

### DEV-MODE
// Insert new service
POST {{url}}/services/
Content-Type: application/json

[
  {
    "service_name": "Edenor"
  }
]

### DEV-MODE
//  Deletes a service
DELETE {{url}}/services/
  ?names=Edenor

### 
// Get all services with revision status
GET {{url}}/services/statuses

### DEV-MODE
// Toggle service status
POST {{url}}/services/statuses
  ?toggle=Edenor

