@hostname = localhost
@port = 3000
@extra-url = api
@version = v1
@host = {{hostname}}:{{port}}/{{extra-url}}/{{version}}

###
# Ping
GET http://{{hostname}}:{{port}}/ping HTTP/1.1

###
# Get all services with revision status
GET http://{{host}}/services/statuses HTTP/1.1
content-type: application/json

